"""Add subscription system tables

Revision ID: 8ea1de3885be
Revises: 
Create Date: 2025-12-16 11:21:03.631474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ea1de3885be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price_monthly', sa.BigInteger(), nullable=False),
    sa.Column('price_yearly', sa.BigInteger(), nullable=True),
    sa.Column('max_agents', sa.Integer(), nullable=False),
    sa.Column('max_devices', sa.Integer(), nullable=False),
    sa.Column('max_monthly_tokens', sa.BigInteger(), nullable=False),
    sa.Column('max_knowledge_base_size_mb', sa.Integer(), nullable=False),
    sa.Column('max_tts_minutes_monthly', sa.Integer(), nullable=False),
    sa.Column('enable_api_access', sa.Boolean(), nullable=False),
    sa.Column('enable_webhook', sa.Boolean(), nullable=False),
    sa.Column('enable_custom_branding', sa.Boolean(), nullable=False),
    sa.Column('enable_priority_support', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plan_name'), 'subscription_plan', ['name'], unique=True)
    op.create_table('subscription_payment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('payment_method', sa.Enum('BANK_TRANSFER', 'MOMO', 'ZALOPAY', 'VNPAY', name='paymentmethod'), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('payment_proof_image_base64', sa.Text(), nullable=True),
    sa.Column('transaction_note', sa.String(length=500), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('account_holder', sa.String(length=100), nullable=True),
    sa.Column('transfer_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='paymentstatus'), nullable=False),
    sa.Column('reviewed_by_admin_id', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plan.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_payment_created_at'), 'subscription_payment', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_payment_status'), 'subscription_payment', ['status'], unique=False)
    op.create_index(op.f('ix_subscription_payment_user_id'), 'subscription_payment', ['user_id'], unique=False)
    op.create_table('usage_tracker',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tracking_date', sa.Date(), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_llm_requests', sa.Integer(), nullable=False),
    sa.Column('total_tts_requests', sa.Integer(), nullable=False),
    sa.Column('total_tts_minutes', sa.Integer(), nullable=False),
    sa.Column('total_asr_requests', sa.Integer(), nullable=False),
    sa.Column('total_webhook_calls', sa.Integer(), nullable=False),
    sa.Column('active_agents', sa.Integer(), nullable=False),
    sa.Column('active_devices', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_size_mb', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_user_date', 'usage_tracker', ['user_id', 'tracking_date'], unique=False)
    op.create_index(op.f('ix_usage_tracker_tracking_date'), 'usage_tracker', ['tracking_date'], unique=False)
    op.create_index(op.f('ix_usage_tracker_user_id'), 'usage_tracker', ['user_id'], unique=False)
    op.create_table('user_subscription',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'EXPIRED', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'YEARLY', 'LIFETIME', name='subscriptionbillingcycle'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_tokens_used', sa.BigInteger(), nullable=False),
    sa.Column('monthly_tts_minutes_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscription_status'), 'user_subscription', ['status'], unique=False)
    op.create_index(op.f('ix_user_subscription_user_id'), 'user_subscription', ['user_id'], unique=False)
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.drop_index(op.f('ix_user_subscription_user_id'), table_name='user_subscription')
    op.drop_index(op.f('ix_user_subscription_status'), table_name='user_subscription')
    op.drop_table('user_subscription')
    op.drop_index(op.f('ix_usage_tracker_user_id'), table_name='usage_tracker')
    op.drop_index(op.f('ix_usage_tracker_tracking_date'), table_name='usage_tracker')
    op.drop_index('idx_usage_user_date', table_name='usage_tracker')
    op.drop_table('usage_tracker')
    op.drop_index(op.f('ix_subscription_payment_user_id'), table_name='subscription_payment')
    op.drop_index(op.f('ix_subscription_payment_status'), table_name='subscription_payment')
    op.drop_index(op.f('ix_subscription_payment_created_at'), table_name='subscription_payment')
    op.drop_table('subscription_payment')
    op.drop_index(op.f('ix_subscription_plan_name'), table_name='subscription_plan')
    op.drop_table('subscription_plan')
    # ### end Alembic commands ###
