"""re_add_token_blacklist_table

Revision ID: d53581e837e5
Revises: 21411fd83412
Create Date: 2025-12-21 18:30:54.292556

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'd53581e837e5'
down_revision: Union[str, None] = 'd5262552b7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
