// Re-export pages here — Xiaozhi CE (Community Edition)
export { LoginPage } from "./LoginPage";
export { default as ChatPage } from "./ChatPage";
export { RegisterPage } from "./RegisterPage";
export { ProfilePage } from "./ProfilePage";
export { SettingsPage } from "./SettingsPage";
export { NotFoundPage } from "./NotFoundPage";
export { AgentsPage } from "./AgentsPage";
export { DevicesPage } from "./DevicesPage";
export { DeviceDetailPage } from "./DeviceDetailPage";
export { AgentDetailPage } from "./AgentDetailPage";
export { AgentKnowledgePage } from "./AgentKnowledgePage";
export { AgentKnowledgePageV2 } from "./AgentKnowledgePageV2";
export { AgentMemoryPage } from "./AgentMemoryPage";
export { AgentHistoryPage } from "./AgentHistoryPage";
export { ProvidersPage } from "./ProvidersPage";
export { ToolsPage } from "./ToolsPage";
export { TemplatesPage } from "./TemplatesPage";
export { TemplateDetailPage } from "./TemplateDetailPage";
export { TemplateEditPage } from "./TemplateEditPage";
export { McpConfigsPage } from "./McpConfigsPage";
export { DeviceCustomizePage } from "./DeviceCustomizePage";
export { FirmwareFlasherPage } from "./FirmwareFlasherPage";
export { FirmwareManagementPage } from "./FirmwareManagementPage";
export { McpEndpointPage } from "./McpEndpointPage";
export { AssetTemplatesPage } from "./AssetTemplatesPage";
export { MemoryPage } from "./MemoryPage";
export { MarketplacePage } from "./MarketplacePage";
export { DisplayCustomizerPage } from "./DisplayCustomizerPage";
export { default as VoiceLibraryPage } from "./VoiceLibraryPage";
export { AssetGeneratorPage } from "./AssetGeneratorPage";
export { EmojiPackPage } from "./EmojiPackPage";
export { EmojiPackEditorPage } from "./EmojiPackEditorPage";
